# Site Information
site_name: Server Setup Guide
site_description: A guide of how I've set up my home server.
site_author: moonstar-x
site_url: https://moonstar-x.dev/server-setup/

# Repo
repo_name: 'GitHub: moonstar-x'
repo_url: https://github.com/moonstar-x
edit_uri: ''

# Social
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/moonstar-x
      name: moonstar-x's GitHub Profile
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/moonstar_x99
      name: moonstar-x on Twitter
    - icon: fontawesome/brands/discord
      link: https://discord.gg/mhj3Zsv
      name: moonstar-x's Discord Server
    - icon: fontawesome/solid/globe-americas
      link: https://moonstar-x.dev
      name: moonstar-x's Website
    - icon: fontawesome/solid/coffee
      link: https://ko-fi.com/moonstar_x
      name: Buy moonstar-x a coffee

# Copyright
copyright: Copyright &copy; 2021 moonstar-x


# Theme Customization
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: deep orange
      accent: orange
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: orange
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/star
    repo: fontawesome/brands/github
  language: en
  direction: ltr
  favicon: assets/favicon.ico
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tracking
    - search.suggest
    - search.highlight

# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.betterem
  - pymdownx.highlight
  - pymdownx.superfences

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date

# Extras
extra_css:
  - stylesheets/extra.css

# Navigation
nav:
  - Home: index.md
  - Setting-up:
    - Linux Server:
      - 0. Introduction: setting-up/linux/index.md
      - 1. OS Installation: setting-up/linux/os-installation.md
      - 2. Packages: setting-up/linux/packages.md
      - 3. Mounting Drives: setting-up/linux/mounting-drives.md
      - 4. Docker: setting-up/linux/docker.md
      - 5. Custom Scripts: setting-up/linux/custom-scripts.md
      - 6. Networking: setting-up/linux/networking.md
  - Services:
    - Cloudflared (Native): services/cloudflared.md
    - Samba (Native): services/samba.md
    - Analytics:
      - Initialization: services/analytics/index.md
      - Plausible: services/analytics/plausible.md
    - Automation:
      - Initialization: services/automation/index.md
      - Custom Automation Service: services/automation/automation-service.md
      - Smart Home: services/automation/smart-home.md
    - Discord Bots:
      - Initialization: services/discord-bots/index.md
      - Free Games Notifier: services/discord-bots/free-games-notifier.md
      - JDA Music Bot: services/discord-bots/jda-music-bot.md
      - Music 24/7 Bot: services/discord-bots/music-24-7.md
      - Text-to-Speech Bot: services/discord-bots/tts-bot.md
    - Docker:
      - Initialization: services/docker/index.md
      - Portainer: services/docker/portainer.md
      - Fleet: services/docker/fleet.md
    - Data:
      - Initialization: services/data/index.md
      - Ghost: services/data/ghost.md
      - Gitea: services/data/gitea.md
      - Jenkins: services/data/jenkins.md
      - Nextcloud: services/data/nextcloud.md
    - Games:
      - Initialization: services/games/index.md
      - ZeroTier-One: services/games/zerotier.md
      - TeamSpeak 3: services/games/teamspeak.md
      - EmulatorJS: services/games/emulatorjs.md
      - Arma 3 (Native): services/games/arma3.md
      - Assetto Corsa: services/games/assettocorsa.md
      - Minecraft (Paper): services/games/minecraft-paper.md
      - Valheim: services/games/valheim.md
    - Media:
      - Initialization: services/media/index.md
      - FreshRSS: services/media/freshrss.md
      - Jellyfin + EmbyStat: services/media/jellyfin-embystat.md
      - Kavita: services/media/kavita.md
      - Media Acquisition: services/media/media-acquisition.md
      - PiGallery 2: services/media/pigallery-2.md
      - Plex + Tautulli + Synclounge: services/media/plex-tautulli-synclounge.md
      - Reddit Slideshow: services/media/reddit-slideshow.md
    - Monitoring:
      - Initialization: services/monitoring/index.md
      - Grafana: services/monitoring/grafana.md
      - LibreSpeed: services/monitoring/librespeed.md
      - Prometheus: services/monitoring/prometheus.md
      - Scrutiny: services/monitoring/scrutiny.md
    - Other:
      - Initialization: services/other/index.md
      - Homepage: services/other/homepage.md
      - Reactive Resume: services/other/rxresume.md
      - RTMP Simulcast: services/other/rtmp-simulcast.md
