# Site Information
site_name: Server Setup Guide
site_description: A guide on how I've set up my self-hosted services.
site_author: moonstar-x
site_url: https://moonstar-x.dev/server-setup/

# Repo
repo_name: 'GitHub: moonstar-x'
repo_url: https://github.com/moonstar-x
edit_uri: ''

# Social
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/moonstar-x
      name: moonstar-x's GitHub Profile
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/moonstar_x99
      name: moonstar-x on X
    - icon: fontawesome/brands/discord
      link: https://discord.gg/mhj3Zsv
      name: moonstar-x's Discord Server
    - icon: fontawesome/solid/earth-americas
      link: https://moonstar-x.dev
      name: moonstar-x's Website

# Copyright
copyright: Copyright &copy; 2025 moonstar-x

# Theme Customization
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: black
      accent: indigo
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: yellow
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/star
    repo: fontawesome/brands/github
  language: en
  direction: ltr
  favicon: assets/favicon.ico
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tracking
    - navigation.expand
    - search.suggest
    - search.highlight

# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.betterem
  - pymdownx.highlight
  - pymdownx.superfences

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date

# Extras
extra_css:
  - stylesheets/extra.css

# Navigation
nav:
  - Home: index.md
  - dev-ec-uio-1:
    - Configuration:
      - 0. Introduction: servers/dev-ec-uio-1/configuration/index.md
      - 1. Installation: servers/dev-ec-uio-1/configuration/installation.md
      - 2. Docker: servers/dev-ec-uio-1/configuration/docker.md
      - 3. Mounting Drives: servers/dev-ec-uio-1/configuration/mounting-drives.md
      - 4. Custom Scripts: servers/dev-ec-uio-1/configuration/custom-scripts.md
    - Services:
      - Introduction: servers/dev-ec-uio-1/services/index.md
      - Development:
        - Initialization: servers/dev-ec-uio-1/services/development/index.md
        - Gitea: servers/dev-ec-uio-1/services/development/gitea.md
        - Gitea Runners: servers/dev-ec-uio-1/services/development/gitea-runners.md
        - Kroki: servers/dev-ec-uio-1/services/development/kroki.md
        - Penpot: servers/dev-ec-uio-1/services/development/penpot.md
      - Management:
        - Initialization: servers/dev-ec-uio-1/services/management/index.md
        - Portainer Agent: servers/dev-ec-uio-1/services/management/portainer-agent.md
      - Networking:
        - Initialization: servers/dev-ec-uio-1/services/networking/index.md
        - Cloudflared: servers/dev-ec-uio-1/services/networking/cloudflared.md
        - Tailscale: servers/dev-ec-uio-1/services/networking/tailscale.md
        - Traefik: servers/dev-ec-uio-1/services/networking/traefik.md
  - misc-ec-uio-1:
    - Configuration:
      - 0. Introduction: servers/misc-ec-uio-1/configuration/index.md
      - 1. Installation: servers/misc-ec-uio-1/configuration/installation.md
      - 2. Docker: servers/misc-ec-uio-1/configuration/docker.md
      - 3. Mounting Drives: servers/misc-ec-uio-1/configuration/mounting-drives.md
      - 4. Custom Scripts: servers/misc-ec-uio-1/configuration/custom-scripts.md
    - Services:
      - Introduction: servers/misc-ec-uio-1/services/index.md
      - Management:
        - Initialization: servers/misc-ec-uio-1/services/management/index.md
        - Portainer Agent: servers/misc-ec-uio-1/services/management/portainer-agent.md
      - Networking:
        - Initialization: servers/misc-ec-uio-1/services/networking/index.md
        - Samba: servers/misc-ec-uio-1/services/networking/samba.md
        - Tailscale: servers/misc-ec-uio-1/services/networking/tailscale.md
        - ZeroTier-One: servers/misc-ec-uio-1/services/networking/zerotier.md
  - misc-us-east-1:
    - Configuration:
      - 0. Introduction: servers/misc-us-east-1/configuration/index.md
      - 1. Installation: servers/misc-us-east-1/configuration/installation.md
      - 2. Docker: servers/misc-us-east-1/configuration/docker.md
      - 3. Custom Scripts: servers/misc-us-east-1/configuration/custom-scripts.md
  - deploy-us-east-1:
    - Configuration:
      - 0. Introduction: servers/deploy-us-east-1/configuration/index.md
      - 1. Installation: servers/deploy-us-east-1/configuration/installation.md
      - 2. Docker: servers/deploy-us-east-1/configuration/docker.md
      - 3. Custom Scripts: servers/deploy-us-east-1/configuration/custom-scripts.md
    - Management:
      - Initialization: servers/deploy-us-east-1/services/management/index.md
      - Portainer Agent: servers/deploy-us-east-1/services/management/portainer-agent.md
    - Networking:
      - Initialization: servers/deploy-us-east-1/services/networking/index.md
      - Tailscale: servers/deploy-us-east-1/services/networking/tailscale.md
