# Site Information
site_name: Server Setup Guide
site_description: A guide on how I've set up my self-hosted services.
site_author: moonstar-x
site_url: https://moonstar-x.dev/server-setup/

# Repo
repo_name: 'GitHub: moonstar-x'
repo_url: https://github.com/moonstar-x
edit_uri: ''

# Social
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/moonstar-x
      name: moonstar-x's GitHub Profile
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/moonstar_x99
      name: moonstar-x on X
    - icon: fontawesome/brands/discord
      link: https://discord.gg/mhj3Zsv
      name: moonstar-x's Discord Server
    - icon: fontawesome/solid/earth-americas
      link: https://moonstar-x.dev
      name: moonstar-x's Website

# Copyright
copyright: Copyright &copy; 2025 moonstar-x

# Theme Customization
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: black
      accent: indigo
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: yellow
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/star
    repo: fontawesome/brands/github
  language: en
  direction: ltr
  favicon: assets/favicon.ico
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tracking
    - navigation.expand
    - search.suggest
    - search.highlight

# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.betterem
  - pymdownx.highlight
  - pymdownx.superfences

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date

# Extras
extra_css:
  - stylesheets/extra.css

# Navigation
nav:
  - Home: index.md
  - dev-ec-uio-1:
    - Configuration:
      - 0. Introduction: servers/dev-ec-uio-1/configuration/index.md
      - 1. Installation: servers/dev-ec-uio-1/configuration/installation.md
      - 2. Docker: servers/dev-ec-uio-1/configuration/docker.md
      - 3. Mounting Drives: servers/dev-ec-uio-1/configuration/mounting-drives.md
      - 4. Custom Scripts: servers/dev-ec-uio-1/configuration/custom-scripts.md
    - Services:
      - Introduction: servers/dev-ec-uio-1/services/index.md
      - AI:
        - Initialization: servers/dev-ec-uio-1/services/ai/index.md
        - Langfuse: servers/dev-ec-uio-1/services/ai/langfuse.md
        - Ollama: servers/dev-ec-uio-1/services/ai/ollama.md
        - Open WebUI: servers/dev-ec-uio-1/services/ai/open-webui.md
      - Data:
        - Initialization: servers/dev-ec-uio-1/services/data/index.md
        - Wakapi: servers/dev-ec-uio-1/services/data/wakapi.md
      - Development:
        - Initialization: servers/dev-ec-uio-1/services/development/index.md
        - Gitea: servers/dev-ec-uio-1/services/development/gitea.md
        - Gitea Runners: servers/dev-ec-uio-1/services/development/gitea-runners.md
        - Glitchtip: servers/dev-ec-uio-1/services/development/glitchtip.md
        - Kroki: servers/dev-ec-uio-1/services/development/kroki.md
        - Penpot: servers/dev-ec-uio-1/services/development/penpot.md
        - Sonarqube: servers/dev-ec-uio-1/services/development/sonarqube.md
      - Management:
        - Initialization: servers/dev-ec-uio-1/services/management/index.md
        - Portainer Agent: servers/dev-ec-uio-1/services/management/portainer-agent.md
      - Networking:
        - Initialization: servers/dev-ec-uio-1/services/networking/index.md
        - Cloudflared: servers/dev-ec-uio-1/services/networking/cloudflared.md
        - Tailscale: servers/dev-ec-uio-1/services/networking/tailscale.md
        - Traefik: servers/dev-ec-uio-1/services/networking/traefik.md
  - misc-ec-uio-1:
    - Configuration:
      - 0. Introduction: servers/misc-ec-uio-1/configuration/index.md
      - 1. Installation: servers/misc-ec-uio-1/configuration/installation.md
      - 2. Docker: servers/misc-ec-uio-1/configuration/docker.md
      - 3. Mounting Drives: servers/misc-ec-uio-1/configuration/mounting-drives.md
      - 4. Custom Scripts: servers/misc-ec-uio-1/configuration/custom-scripts.md
    - Services:
      - Introduction: servers/misc-ec-uio-1/services/index.md
      - Automation:
        - Initialization: servers/misc-ec-uio-1/services/automation/index.md
        - Homebridge: servers/misc-ec-uio-1/services/automation/homebridge.md
        - n8n: servers/misc-ec-uio-1/services/automation/n8n.md
      - Data:
        - Initialization: servers/misc-ec-uio-1/services/data/index.md
        - Nextcloud: servers/misc-ec-uio-1/services/data/nextcloud.md
        - Pairdrop: servers/misc-ec-uio-1/services/data/pairdrop.md
        - Reactive Resume: servers/misc-ec-uio-1/services/data/rx-resume.md
      - Downloads:
        - Initialization: servers/misc-ec-uio-1/services/downloads/index.md
        - Bazarr: servers/misc-ec-uio-1/services/downloads/bazarr.md
        - JDownloader: servers/misc-ec-uio-1/services/downloads/jdownloader.md
        - Overseerr: servers/misc-ec-uio-1/services/downloads/overseerr.md
        - Prowlarr: servers/misc-ec-uio-1/services/downloads/prowlarr.md
        - Radarr: servers/misc-ec-uio-1/services/downloads/radarr.md
        - Sonarr: servers/misc-ec-uio-1/services/downloads/sonarr.md
        - Transmission: servers/misc-ec-uio-1/services/downloads/transmission.md
      - Games:
        - Initialization: servers/misc-ec-uio-1/services/games/index.md
        - Assetto Corsa: servers/misc-ec-uio-1/services/games/assetto-corsa.md
        - Romm: servers/misc-ec-uio-1/services/games/romm.md
        - TeamSpeak 3: servers/misc-ec-uio-1/services/games/teamspeak.md
      - Management:
        - Initialization: servers/misc-ec-uio-1/services/management/index.md
        - Portainer Agent: servers/misc-ec-uio-1/services/management/portainer-agent.md
      - Media:
        - Initialization: servers/misc-ec-uio-1/services/media/index.md
        - Jellyfin: servers/misc-ec-uio-1/services/media/jellyfin.md
        - Kavita: servers/misc-ec-uio-1/services/media/kavita.md
        - Plex: servers/misc-ec-uio-1/services/media/plex.md
        - Restreamer: servers/misc-ec-uio-1/services/media/restreamer.md
        - Tautulli: servers/misc-ec-uio-1/services/media/tautulli.md
      - Networking:
        - Initialization: servers/misc-ec-uio-1/services/networking/index.md
        - Cloudflared: servers/misc-ec-uio-1/services/networking/cloudflared.md
        - Samba: servers/misc-ec-uio-1/services/networking/samba.md
        - Tailscale: servers/misc-ec-uio-1/services/networking/tailscale.md
        - Traefik: servers/misc-ec-uio-1/services/networking/traefik.md
        - ZeroTier-One: servers/misc-ec-uio-1/services/networking/zerotier.md
  - nano-ec-uio-1:
    - Configuration:
      - 0. Introduction: servers/nano-ec-uio-1/configuration/index.md
      - 1. Installation: servers/nano-ec-uio-1/configuration/installation.md
      - 2. Docker: servers/nano-ec-uio-1/configuration/docker.md
      - 3. Monitor: servers/nano-ec-uio-1/configuration/monitor.md
    - Services:
      - Management:
        - Initialization: servers/nano-ec-uio-1/services/management/index.md
        - Portainer Agent: servers/nano-ec-uio-1/services/management/portainer-agent.md
      - Networking:
        - Initialization: servers/nano-ec-uio-1/services/networking/index.md
        - Tailscale: servers/nano-ec-uio-1/services/networking/tailscale.md
  - misc-us-east-1:
    - Configuration:
      - 0. Introduction: servers/misc-us-east-1/configuration/index.md
      - 1. Installation: servers/misc-us-east-1/configuration/installation.md
      - 2. Docker: servers/misc-us-east-1/configuration/docker.md
      - 3. Custom Scripts: servers/misc-us-east-1/configuration/custom-scripts.md
    - Services:
      - Introduction: servers/misc-us-east-1/services/index.md
      - Data:
        - Initialization: servers/misc-us-east-1/services/data/index.md
        - Actual: servers/misc-us-east-1/services/data/actual.md
        - Maybe: servers/misc-us-east-1/services/data/maybe.md
        - Memos: servers/misc-us-east-1/services/data/memos.md
        - Wallos: servers/misc-us-east-1/services/data/wallos.md
      - Management:
        - Initialization: servers/misc-us-east-1/services/management/index.md
        - Glance: servers/misc-us-east-1/services/management/glance.md
        - Portainer: servers/misc-us-east-1/services/management/portainer.md
        - Rustdesk: servers/misc-us-east-1/services/management/rustdesk.md
      - Media:
        - Initialization: servers/misc-us-east-1/services/media/index.md
        - FreshRSS: servers/misc-us-east-1/services/media/freshrss.md
      - Networking:
        - Initialization: servers/misc-us-east-1/services/networking/index.md
        - Cloudflared: servers/misc-us-east-1/services/networking/cloudflared.md
        - Tailscale: servers/misc-us-east-1/services/networking/tailscale.md
        - Traefik: servers/misc-us-east-1/services/networking/traefik.md
  - deploy-us-east-1:
    - Configuration:
      - 0. Introduction: servers/deploy-us-east-1/configuration/index.md
      - 1. Installation: servers/deploy-us-east-1/configuration/installation.md
      - 2. Docker: servers/deploy-us-east-1/configuration/docker.md
      - 3. Custom Scripts: servers/deploy-us-east-1/configuration/custom-scripts.md
    - Deployments:
      - Introduction: servers/deploy-us-east-1/deployments/index.md
      - Discord - Free Games Notifier: servers/deploy-us-east-1/deployments/discord-free-games-notifier.md
      - Discord - Text-to-Speech: servers/deploy-us-east-1/deployments/discord-text-to-speech.md
    - Services:
      - Introduction: servers/deploy-us-east-1/services/index.md
      - Management:
        - Initialization: servers/deploy-us-east-1/services/management/index.md
        - Portainer Agent: servers/deploy-us-east-1/services/management/portainer-agent.md
      - Networking:
        - Initialization: servers/deploy-us-east-1/services/networking/index.md
        - Tailscale: servers/deploy-us-east-1/services/networking/tailscale.md
  - dev-eu-west-1:
    - Configuration:
      - 0. Introduction: servers/dev-eu-west-1/configuration/index.md
      - 1. Installation: servers/dev-eu-west-1/configuration/installation.md
      - 2. Docker: servers/dev-eu-west-1/configuration/docker.md
      - 3. Custom Scripts: servers/dev-eu-west-1/configuration/custom-scripts.md
    - Services:
      - Introduction: servers/dev-eu-west-1/services/index.md
      - Analytics:
        - Initialization: servers/dev-eu-west-1/services/analytics/index.md
        - Umami: servers/dev-eu-west-1/services/analytics/umami.md
      - Development:
        - Initialization: servers/dev-eu-west-1/services/development/index.md
        - Gitea: servers/dev-eu-west-1/services/development/gitea.md
      - Management:
          - Initialization: servers/dev-eu-west-1/services/management/index.md
          - Portainer Agent: servers/dev-eu-west-1/services/management/portainer-agent.md
      - Networking:
          - Initialization: servers/dev-eu-west-1/services/networking/index.md
          - Tailscale: servers/dev-eu-west-1/services/networking/tailscale.md
          - Traefik: servers/dev-eu-west-1/services/networking/traefik.md
      - Observability:
        - Initialization: servers/dev-eu-west-1/services/observability/index.md
        - Uptime Kuma: servers/dev-eu-west-1/services/observability/uptime-kuma.md
