# Site Information
site_name: Server Setup Guide
site_description: A guide on how I've set up my self-hosted services.
site_author: moonstar-x
site_url: https://moonstar-x.dev/server-setup/

# Repo
repo_name: 'GitHub: moonstar-x'
repo_url: https://github.com/moonstar-x
edit_uri: ''

# Social
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/moonstar-x
      name: moonstar-x's GitHub Profile
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/moonstar_x99
      name: moonstar-x on X
    - icon: fontawesome/brands/discord
      link: https://discord.gg/mhj3Zsv
      name: moonstar-x's Discord Server
    - icon: fontawesome/solid/earth-americas
      link: https://moonstar-x.dev
      name: moonstar-x's Website

# Copyright
copyright: Copyright &copy; 2025 moonstar-x

# Theme Customization
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: black
      accent: indigo
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: yellow
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/star
    repo: fontawesome/brands/github
  language: en
  direction: ltr
  favicon: assets/favicon.ico
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tracking
    - navigation.expand
    - search.suggest
    - search.highlight

# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.betterem
  - pymdownx.highlight
  - pymdownx.superfences

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date

# Extras
extra_css:
  - stylesheets/extra.css

# Navigation
nav:
  - Home: index.md
