# Site Information
site_name: Server Setup Guide
site_description: A guide of how I've set up my home server.
site_author: moonstar-x
site_url: https://moonstar-x.dev/server-setup/

# Repo
repo_name: 'GitHub: moonstar-x'
repo_url: https://github.com/moonstar-x
edit_uri: ''

# Social
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/moonstar-x
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/moonstar_x99
    - icon: fontawesome/solid/globe-americas
      link: https://moonstar-x.dev

# Copyright
copyright: Copyright &copy; 2021 moonstar-x

# Navigation
nav:
  - Home: index.md
  - Setting-up: 
    - OS Installation: setting-up/os-installation.md
    - Packages: setting-up/packages.md
    - Mounting Drives: setting-up/mounting-drives.md
    - Networking: setting-up/networking.md
    - Docker: setting-up/docker.md
  - Services:
    - Samba (Native): services/samba.md
    - Media:
      - Initialization: services/media/index.md
      - Jellyfin: services/media/jellyfin.md
      - Plex: services/media/plex.md
      - Tautulli: services/media/tautulli.md
      - Transmission: services/media/transmission.md
      - Sonarr: services/media/sonarr.md
      - Radarr: services/media/radarr.md
      - Jackett: services/media/jackett.md
      - JDownloader: services/media/jdownloader.md
    - Data:
      - Initialization: services/data/index.md
      - Gitea: services/data/gitea.md
    - Other:
      - Initialization: services/other/index.md
      - RTMP Simulcast: services/other/rtmp-simulcast.md
      - Webframes: services/other/webframes.md
  - Discord Bots:
    - Initialization: discord-bots/index.md
    - Free Games Notifier: discord-bots/free-games-notifier.md
    - Text-to-Speech Bot: discord-bots/tts-bot.md
    - Music 24/7 Bot: discord-bots/music-24-7.md
    - JDA Music Bot: discord-bots/jda-music-bot.md

# Theme Customization
theme:
  name: material
  palette:
    - scheme: default
      primary: deep orange
      accent: orange
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: orange
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/star
    repo: fontawesome/brands/github
  language: en
  direction: ltr
  favicon: assets/favicon.ico
  features:
    navigation.tabs: true
    navigation.sections: true

# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.betterem
  - pymdownx.highlight
  - pymdownx.superfences

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date

# Google Analytics
google_analytics:
  - UA-167966432-2
  - auto