# Site Information
site_name: Server Setup Guide
site_description: A guide of how I've set up my home server.
site_author: moonstar-x
site_url: https://moonstar-x.dev/server-setup/

# Repo
repo_name: 'GitHub: moonstar-x'
repo_url: https://github.com/moonstar-x
edit_uri: ''

# Social
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/moonstar-x
      name: moonstar-x's GitHub Profile
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/moonstar_x99
      name: moonstar-x on Twitter
    - icon: fontawesome/brands/discord
      link: https://discord.gg/mhj3Zsv
      name: moonstar-x's Discord Server
    - icon: fontawesome/solid/globe-americas
      link: https://moonstar-x.dev
      name: moonstar-x's Website
    - icon: fontawesome/solid/coffee
      link: https://ko-fi.com/moonstar_x
      name: Buy moonstar-x a coffee

# Copyright
copyright: Copyright &copy; 2021 moonstar-x


# Theme Customization
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: deep orange
      accent: orange
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: orange
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/star
    repo: fontawesome/brands/github
  language: en
  direction: ltr
  favicon: assets/favicon.ico
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tracking
    - search.suggest
    - search.highlight

# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.betterem
  - pymdownx.highlight
  - pymdownx.superfences

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date

# Extras
extra_css:
  - stylesheets/extra.css

# Navigation
nav:
  - Home: index.md
  - Setting-up: 
    - OS Installation: setting-up/os-installation.md
    - Packages: setting-up/packages.md
    - Mounting Drives: setting-up/mounting-drives.md
    - Networking: setting-up/networking.md
    - Docker: setting-up/docker.md
    - Custom Scripts: setting-up/custom-scripts.md
  - Services:
    - Samba (Native): services/samba.md
    - Cloudflared (Native): services/cloudflared.md
    - Docker:
      - Initialization: services/docker/index.md
      - Portainer: services/docker/portainer.md
      - Fleet: services/docker/fleet.md
    - Media:
      - Initialization: services/media/index.md
      - FreshRSS: services/media/freshrss.md
      - Kavita: services/media/kavita.md
      - Jellyfin + EmbyStat: services/media/jellyfin-embystat.md
      - Plex + Tautulli + Synclounge: services/media/plex-tautulli-synclounge.md
      - Media Acquisition: services/media/media-acquisition.md
    - Data:
      - Initialization: services/data/index.md
      - Ghost: services/data/ghost.md
      - Nextcloud: services/data/nextcloud.md
      - Gitea: services/data/gitea.md
      - Jenkins: services/data/jenkins.md
    - Monitoring:
      - Initialization: services/monitoring/index.md
      - LibreSpeed: services/monitoring/librespeed.md
      - Scrutiny: services/monitoring/scrutiny.md
    - Automation:
      - Initialization: services/automation/index.md
      - Custom Automation Service: services/automation/automation-service.md
      - Smart Home: services/automation/smart-home.md
    - Analytics:
      - Initialization: services/analytics/index.md
      - Plausible: services/analytics/plausible.md
    - Other:
      - Initialization: services/other/index.md
      - RTMP Simulcast: services/other/rtmp-simulcast.md
      - Homepage: services/other/homepage.md
      - Reactive Resume: services/other/rxresume.md
  - Server Monitoring:
    - Introduction: server-monitoring/introduction.md
    - In Server:
      - Initialization: server-monitoring/in-server/index.md
      - Prometheus: server-monitoring/in-server/prometheus.md
    - In Monitor:
      - Initialization: server-monitoring/in-monitor/index.md
      - Configuration: server-monitoring/in-monitor/configuration.md
      - Grafana: server-monitoring/in-monitor/grafana.md
      - Portainer (Agent): server-monitoring/in-monitor/portainer-agent.md
  - Discord Bots:
    - Initialization: discord-bots/index.md
    - Free Games Notifier: discord-bots/free-games-notifier.md
    - Text-to-Speech Bot: discord-bots/tts-bot.md
    - Music 24/7 Bot: discord-bots/music-24-7.md
    - JDA Music Bot: discord-bots/jda-music-bot.md
  - Game Servers:
    - Initialization: games/index.md
    - ZeroTier-One: games/zerotier.md
    - TeamSpeak 3: games/teamspeak.md
    - EmulatorJS: games/emulatorjs.md
    - Arma 3 (Native): games/arma3.md
    - Assetto Corsa: games/assettocorsa.md
    - Minecraft (Paper): games/minecraft-paper.md
    - Valheim: games/valheim.md
  - Deprecated Services:
    - Media:
      - Information: deprecated/media/index.md
      - Miniflux: deprecated/media/miniflux.md
      - Media Acquisition: deprecated/media/media-acquisition.md
    - Data:
      - Information: deprecated/data/index.md
      - Drone: deprecated/data/drone.md
      - Nexus: deprecated/data/nexus.md
    - Automation:
      - Information: deprecated/automation/index.md
      - n8n: deprecated/automation/n8n.md
    - Other:
      - Information: deprecated/other/index.md
      - Webframes: deprecated/other/webframes.md
