# Site Information
site_name: Server Setup Guide
site_description: A guide of how I've set up my home server.
site_author: moonstar-x
site_url: https://moonstar-x.dev/server-setup/

# Repo
repo_name: 'GitHub: moonstar-x'
repo_url: https://github.com/moonstar-x
edit_uri: ''

# Social
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/moonstar-x
      name: moonstar-x's GitHub Profile
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/moonstar_x99
      name: moonstar-x on Twitter
    - icon: fontawesome/brands/discord
      link: https://discord.gg/mhj3Zsv
      name: moonstar-x's Discord Server
    - icon: fontawesome/solid/globe-americas
      link: https://moonstar-x.dev
      name: moonstar-x's Website
    - icon: fontawesome/solid/coffee
      link: https://ko-fi.com/moonstar_x
      name: Buy moonstar-x a coffee

# Copyright
copyright: Copyright &copy; 2021 moonstar-x

# Theme Customization
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: deep orange
      accent: orange
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: orange
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/star
    repo: fontawesome/brands/github
  language: en
  direction: ltr
  favicon: assets/favicon.ico
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tracking
    - search.suggest
    - search.highlight

# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.betterem
  - pymdownx.highlight
  - pymdownx.superfences

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date

# Extras
extra_css:
  - stylesheets/extra.css

# Navigation
nav:
  - Home: index.md
  - Linux/Setting Up:
    - 0. Introduction: linux/setting-up/index.md
    - 1. Installation: linux/setting-up/installation.md
    - 2. Mounting Drives: linux/setting-up/mounting-drives.md
    - 3. Docker: linux/setting-up/docker.md
    - 4. Custom Scripts: linux/setting-up/custom-scripts.md
  - Linux/Services:
    - Introduction: linux/services/index.md
    - Networking:
      - Introduction: linux/services/networking/index.md
      - Cloudflared: linux/services/networking/cloudflared.md
      - Samba: linux/services/networking/samba.md
      - Traefik: linux/services/networking/traefik.md
      - ZeroTier-One: linux/services/networking/zerotier.md
    - Media:
      - Introduction: linux/services/media/index.md
      - FreshRSS: linux/services/media/freshrss.md
      - Kavita: linux/services/media/kavita.md
      - Jellyfin: linux/services/media/jellyfin.md
      - EmbyStat: linux/services/media/embystat.md
      - PiGallery 2: linux/services/media/pigallery-2.md
      - Plex: linux/services/media/plex.md
      - Tautulli: linux/services/media/tautulli.md
      - Synclounge: linux/services/media/synclounge.md
      - Reddit Slideshow: linux/services/media/reddit-slideshow.md
    - Development:
      - Introduction: linux/services/development/index.md
      - Fleet: linux/services/development/fleet.md
      - Gitea: linux/services/development/gitea.md
      - Jenkins: linux/services/development/jenkins.md
    - Observability:
      - Introduction: linux/services/observability/index.md
      - LibreSpeed: linux/services/observability/librespeed.md
      - Prometheus: linux/services/observability/prometheus.md
      - Grafana: linux/services/observability/grafana.md
      - Scrutiny: linux/services/observability/scrutiny.md
    - Discord:
      - Introduction: linux/services/discord/index.md
      - Free Games Notifier: linux/services/discord/free-games-notifier.md
      - JDA Music Bot: linux/services/discord/jda-music-bot.md
      - Music 24/7: linux/services/discord/music-24-7.md
      - Text-to-Speech: linux/services/discord/text-to-speech.md
    - Automation:
      - Introduction: linux/services/automation/index.md
      - Homebridge: linux/services/automation/homebridge.md
    - Data:
      - Introduction: linux/services/data/index.md
      - Actual: linux/services/data/actual.md
      - Nextcloud: linux/services/data/nextcloud.md
      - Reactive Resume: linux/services/data/rx-resume.md
    - Games:
      - Introduction: linux/services/games/index.md
      - TeamSpeak 3: linux/services/games/teamspeak.md
      - Assetto Corsa: linux/services/games/assetto-corsa.md
    - Downloads:
      - Introduction: linux/services/downloads/index.md
      - Transmission: linux/services/downloads/transmission.md
      - JDownloader: linux/services/downloads/jdownloader.md
      - Prowlarr: linux/services/downloads/prowlarr.md
      - Sonarr: linux/services/downloads/sonarr.md
      - Lidarr: linux/services/downloads/lidarr.md
      - Radarr: linux/services/downloads/radarr.md
      - Bazarr: linux/services/downloads/bazarr.md
      - Readarr: linux/services/downloads/readarr.md
      - Ombi: linux/services/downloads/ombi.md
      - OpenBooks: linux/services/downloads/openbooks.md
    - Management:
      - Introduction: linux/services/management/index.md
      - Portainer: linux/services/management/portainer.md
      - Homepage: linux/services/management/homepage.md
  - Bootcamp/Setting Up:
    - 0. Introduction: bootcamp/setting-up/index.md
    - 1. macOS Configuration: bootcamp/setting-up/mac-os-configuration.md
    - 2. Bootcamp: bootcamp/setting-up/bootcamp.md
    - 3. Windows Configuration: bootcamp/setting-up/windows-configuration.md
  - Bootcamp/Game Servers:
    - Introduction: bootcamp/games/index.md
    - Alien Swarm Reactive Drop: bootcamp/games/reactivedrop.md
    - Arma 3: bootcamp/games/arma3.md
    - 'Counter-Strike: Global Offensive': bootcamp/games/csgo.md
    - DayZ: bootcamp/games/dayz.md
    - Left 4 Dead 2: bootcamp/games/l4d2.md
    - No More Room in Hell: bootcamp/games/nmrih.md
    - Sven Coop: bootcamp/games/svencoop.md
    - Valheim: bootcamp/games/valheim.md
