name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  publish:
    name: Publish Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Publish to GH-Pages
        run: mkdocs gh-deploy --force
